import { createBrain } from './brain.js';
import { loadConversation, saveConversation, clearConversation, clearMemory, createMemory, saveMemory, getDeviceId } from './memory.js';
const brain=createBrain();const chat=document.getElementById('chat');const input=document.getElementById('messageInput');const send=document.getElementById('sendButton');const fileInput=document.getElementById('imageFileInput');const filePreview=document.getElementById('filePreview');const attachMenu=document.getElementById('attachMenu');const deviceId=getDeviceId();let history=loadConversation();let selectedFile=null;let selectedImageData='';let selectedDocumentText='';const MAX_DOCUMENT_CHARS=60000;let activeController=null;
function html(text){let safe=String(text).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');safe=safe.replace(/```([a-z0-9_-]+)?\n([\s\S]*?)```/gi,(_,lang,code)=>`<pre class="code-block"><code>${code.trim()}</code><button class="copy-code" type="button">Copier</button></pre>`);safe=safe.replace(/^###\s+(.+)$/gm,'<h4>$1</h4>').replace(/^##\s+(.+)$/gm,'<h3>$1</h3>').replace(/^#\s+(.+)$/gm,'<h2>$1</h2>');return safe.replace(/\*\*(.*?)\*\*/g,'<strong>$1</strong>').replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\n/g,'<br>');}
function show(text,type,persist=true){
 const row=document.createElement('div');row.className=`message-row ${type}`;
 const bubble=document.createElement('div');bubble.className=`bubble ${type}`;bubble.innerHTML=html(text);row.appendChild(bubble);chat.appendChild(row);
 if(persist){history.push({text:String(text),type,time:Date.now()});history=history.slice(-150);saveConversation(history);}
 bubble.querySelectorAll('.copy-code').forEach(button=>button.addEventListener('click',async()=>{const code=button.parentElement.querySelector('code')?.textContent||'';try{await navigator.clipboard.writeText(code);button.textContent='Copié';setTimeout(()=>button.textContent='Copier',1200);}catch{button.textContent='Erreur';}}));
 if(type==='nexus' && persist){
   const actions=document.createElement('div');actions.className='message-actions';
   const copy=document.createElement('button');copy.type='button';copy.textContent='Copier';copy.title='Copier la réponse';
   copy.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(String(text));copy.textContent='Copié';setTimeout(()=>copy.textContent='Copier',1200);}catch{copy.textContent='Erreur';}});
   actions.appendChild(copy);bubble.appendChild(actions);
 }
 chat.scrollTop=chat.scrollHeight;
}
function showUserImage(dataUrl){const row=document.createElement('div');row.className='message-row user';const bubble=document.createElement('div');bubble.className='bubble user image-user-card';const img=document.createElement('img');img.className='attached-image';img.src=dataUrl;img.alt='Image jointe à Nexus AI';bubble.appendChild(img);chat.appendChild(row);row.appendChild(bubble);chat.scrollTop=chat.scrollHeight;}
function escapeHtml(text){return String(text).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');}
function showUserDocument(file,chars){const row=document.createElement('div');row.className='message-row user';const bubble=document.createElement('div');bubble.className='bubble user document-user-card';bubble.innerHTML=`<div class="document-title">📄 ${escapeHtml(file.name)}</div><div class="document-meta">${escapeHtml(file.type||'Document')} · ${chars.toLocaleString('fr-FR')} caractères extraits</div>`;chat.appendChild(row);row.appendChild(bubble);chat.scrollTop=chat.scrollHeight;}
function render(){chat.innerHTML='';if(!history.length){const empty=document.createElement('div');empty.className='empty-state';empty.innerHTML='<div class="empty-logo">N</div><h2>Que puis-je faire pour toi ?</h2><p>Je peux discuter, analyser des images et des documents, répondre à tes questions, générer des images et du code.</p><div class="quick-grid"><button class="quick-card suggestion">Explique-moi le théorème de Pythagore</button><button class="quick-card suggestion">Écris-moi un site HTML simple</button><button class="quick-card suggestion">Crée une image d’un chat réaliste</button><button class="quick-card suggestion">Que sais-tu faire ?</button></div>';chat.appendChild(empty);}else history.forEach(item=>{if(item&&typeof item.text==='string'&&(item.type==='user'||item.type==='nexus'))show(item.text,item.type,false);});bindSuggestions();}
function bindSuggestions(){document.querySelectorAll('.suggestion').forEach(button=>button.addEventListener('click',()=>sendText(button.textContent)));}
function splitQuestions(text){return String(text).replace(/\r/g,'').split(/\n/).map(x=>x.trim()).map(x=>x.replace(/^[-•*]\s+/,'').replace(/^\d+[.)]\s+/,'').trim()).filter(Boolean);}
function setBusy(value){send.disabled=false;input.disabled=value;document.getElementById('imageUploadButton')?.toggleAttribute('disabled',value);send.textContent=value?'×':'↑';send.setAttribute('aria-label',value?'Arrêter la génération':'Envoyer');}function stopGeneration(){activeController?.abort();activeController=null;setBusy(false);}
function isImagePrompt(text){return /\b(cr[ée]e|g[ée]n[èe]re|dessine|fais|produis|fabrique)\b.*\bimage\b/i.test(text)||/\bimage d(?:e|u|des|un|une)\b/i.test(text);}
function isVideoPrompt(text){return /\b(cr[ée]e|g[ée]n[èe]re|fais|fabrique|produis|anime|anim[eé])\b.*\bvid[ée]o\b/i.test(text)||/\bvid[ée]o\b.*\b(cr[ée]e|g[ée]n[èe]re|fais|fabrique|produis|anime|anim[eé])/i.test(text);}
function showVideoLoading(prompt){const row=document.createElement('div');row.className='message-row nexus';const bubble=document.createElement('div');bubble.className='bubble nexus video-card';bubble.innerHTML='<strong>🎬 Création vidéo V2</strong><p class="video-prompt"></p><div class="video-loading"><span></span><span></span><span></span> Génération de la vidéo…</div>';bubble.querySelector('.video-prompt').textContent=prompt;row.appendChild(bubble);chat.appendChild(row);chat.scrollTop=chat.scrollHeight;return bubble;}
async function generateVideo(prompt,bubble){try{const response=await fetch('/api/generate-video',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt,model:'veo',duration:4})});if(!response.ok){const data=await response.json().catch(()=>({}));throw new Error(data?.error||'Le moteur vidéo est indisponible.');}const blob=await response.blob();if(!blob.size)throw new Error('La vidéo générée est vide.');const url=URL.createObjectURL(blob);bubble.querySelector('.video-loading')?.remove();const video=document.createElement('video');video.className='generated-video';video.controls=true;video.playsInline=true;video.preload='metadata';video.src=url;video.setAttribute('aria-label','Vidéo générée par Nexus IA');bubble.appendChild(video);const done=document.createElement('p');done.className='image-status';done.textContent='✅ Vidéo générée.';bubble.appendChild(done);history.push({text:'[Vidéo générée] '+prompt,type:'nexus',time:Date.now()});history=history.slice(-150);saveConversation(history);chat.scrollTop=chat.scrollHeight;}catch(error){bubble.querySelector('.video-loading')?.remove();const box=document.createElement('p');box.className='image-error';box.textContent='⚠️ '+error.message;bubble.appendChild(box);}}
function isEditPrompt(text){return /\b(modifie|modifier|modification|change|changer|remplace|remplacer|enl[èe]ve|enlever|supprime|supprimer|ajoute|ajouter|retouche|retoucher|transforme|transformer|mets|mettre|am[ée]liore|am[ée]liorer)\b/i.test(text);}
function showImageLoading(prompt,title='🎨 Génération d’image'){const row=document.createElement('div');row.className='message-row nexus';const bubble=document.createElement('div');bubble.className='bubble nexus image-card';bubble.innerHTML=`<strong>${title}</strong><p>Demande :</p><div class="image-prompt"></div><div class="image-loading"><span></span><span></span><span></span> Traitement en cours…</div>`;bubble.querySelector('.image-prompt').textContent=prompt;chat.appendChild(row);row.appendChild(bubble);chat.scrollTop=chat.scrollHeight;return bubble;}
function showGeneratedImage(bubble,data,prompt,label='Image générée'){const loading=bubble.querySelector('.image-loading');if(loading)loading.remove();if(data?.url){const img=document.createElement('img');img.className='generated-image';img.src=data.url;img.alt=prompt;img.loading='lazy';bubble.appendChild(img);}else if(data?.b64_json){const img=document.createElement('img');img.className='generated-image';img.src=`data:image/png;base64,${data.b64_json}`;img.alt=prompt;bubble.appendChild(img);}const done=document.createElement('p');done.className='image-status';done.textContent=`✅ ${label}.`;bubble.appendChild(done);history.push({text:`[${label}] ${prompt}`,type:'nexus',time:Date.now()});history=history.slice(-150);saveConversation(history);chat.scrollTop=chat.scrollHeight;}
async function generateImage(prompt,bubble){try{const response=await fetch('/api/generate-image',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt,model:'flux'})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data?.error||'Le moteur d’image est indisponible.');showGeneratedImage(bubble,data,prompt);}catch(error){const loading=bubble.querySelector('.image-loading');if(loading)loading.remove();const errorBox=document.createElement('p');errorBox.className='image-error';errorBox.textContent=`⚠️ ${error.message}`;bubble.appendChild(errorBox);}}
async function editImage(imageData,prompt,bubble){try{const response=await fetch('/api/edit-image',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({imageData,prompt})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data?.error||'Le moteur de modification d’image est indisponible.');showGeneratedImage(bubble,data,prompt,'Image modifiée');}catch(error){const loading=bubble.querySelector('.image-loading');if(loading)loading.remove();const errorBox=document.createElement('p');errorBox.className='image-error';errorBox.textContent=`⚠️ ${error.message}`;bubble.appendChild(errorBox);}}
async function askAI(message,imageData='',documentText='',documentName=''){activeController=new AbortController();const response=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},signal:activeController.signal,body:JSON.stringify({message,imageData,documentText,documentName,history:history.slice(-24),memory:brain.getMemory()})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data?.error||`Erreur serveur (${response.status}).`);if(!data?.text)throw new Error('Le moteur IA n’a renvoyé aucune réponse.');return data.text;}
function fileToDataUrl(file){return new Promise((resolve,reject)=>{if(!file.type.startsWith('image/'))return reject(new Error('Ce fichier n’est pas une image.'));const reader=new FileReader();reader.onload=()=>{const img=new Image();img.onload=()=>{const max=1400;const scale=Math.min(1,max/Math.max(img.width,img.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL('image/jpeg',0.82));};img.onerror=()=>reject(new Error('Impossible de lire cette image.'));img.src=reader.result;};reader.onerror=()=>reject(new Error('Impossible de charger cette image.'));reader.readAsDataURL(file);});}
function limitText(text){const clean=String(text||'').replace(/\u0000/g,'').trim();return clean.length>MAX_DOCUMENT_CHARS?`${clean.slice(0,MAX_DOCUMENT_CHARS)}\n\n[Document tronqué à ${MAX_DOCUMENT_CHARS.toLocaleString('fr-FR')} caractères pour la requête.]`:clean;}
async function extractPdf(file){if(!window.pdfjsLib)throw new Error('Le lecteur PDF n’est pas disponible. Recharge la page puis réessaie.');window.pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';const pdf=await window.pdfjsLib.getDocument({data:await file.arrayBuffer()}).promise;const pages=[];for(let i=1;i<=pdf.numPages;i++){const page=await pdf.getPage(i);const content=await page.getTextContent();pages.push(`--- Page ${i} ---\n${content.items.map(item=>item.str||'').join(' ')}`);}return pages.join('\n\n');}
async function extractDocx(file){if(!window.mammoth)throw new Error('Le lecteur Word n’est pas disponible. Recharge la page puis réessaie.');const result=await window.mammoth.extractRawText({arrayBuffer:await file.arrayBuffer()});return result.value;}
async function extractOdt(file){if(!window.JSZip)throw new Error('Le lecteur LibreOffice n’est pas disponible. Recharge la page puis réessaie.');const zip=await window.JSZip.loadAsync(await file.arrayBuffer());const entry=zip.file('content.xml');if(!entry)throw new Error('Le fichier LibreOffice ne contient pas de contenu lisible.');const xml=await entry.async('text');const doc=new DOMParser().parseFromString(xml,'application/xml');const nodes=[...doc.getElementsByTagName('text:p'),...doc.getElementsByTagName('text:h')];return nodes.map(node=>node.textContent.trim()).filter(Boolean).join('\n\n');}
async function extractTextFile(file){return await file.text();}
async function extractDocument(file){const name=file.name.toLowerCase();if(name.endsWith('.pdf'))return extractPdf(file);if(name.endsWith('.docx'))return extractDocx(file);if(name.endsWith('.odt'))return extractOdt(file);if(name.endsWith('.txt')||name.endsWith('.md')||name.endsWith('.csv')||name.endsWith('.json'))return extractTextFile(file);throw new Error('Format non pris en charge. Utilise PDF, Word .docx, LibreOffice .odt ou un fichier texte.');}
function setFilePreview(file,kind,chars=0){selectedFile=file;filePreview.hidden=false;document.getElementById('fileName').textContent=file.name;document.getElementById('fileMeta').textContent=kind==='image'?'Image prête à analyser ou modifier':`${kind} · ${chars.toLocaleString('fr-FR')} caractères extraits`;}
function clearSelectedFile(){selectedFile=null;selectedImageData='';selectedDocumentText='';filePreview.hidden=true;input.placeholder='Message à Nexus IA...';}
async function handleFile(file){if(!file)return;clearSelectedFile();if(file.type.startsWith('image/')){selectedImageData=await fileToDataUrl(file);setFilePreview(file,'image');input.placeholder='Pose une question sur cette image…';return;}const text=limitText(await extractDocument(file));if(!text)throw new Error('Aucun texte lisible n’a été trouvé dans ce document.');selectedDocumentText=text;setFilePreview(file,'Document',text.length);input.placeholder='Pose une question sur ce document…';}
async function sendText(text){if(activeController){stopGeneration();return;}const questions=splitQuestions(text);if(!questions.length&&!selectedFile)return;const imageForRequest=selectedImageData;const documentForRequest=selectedDocumentText;const fileForRequest=selectedFile;const hadImage=Boolean(imageForRequest);const hadDocument=Boolean(documentForRequest);input.value='';input.style.height='auto';setBusy(true);try{if(hadImage)showUserImage(imageForRequest);if(hadDocument)showUserDocument(fileForRequest,documentForRequest.length);if((hadImage||hadDocument)&&!questions.length)questions.push(hadImage?'Analyse cette image et explique-moi ce que tu observes.':'Résume ce document et explique-moi les points importants.');for(const q of questions){await new Promise(r=>setTimeout(r,120));if(hadImage){if(isEditPrompt(q)){const bubble=showImageLoading(q,'🪄 Modification de l’image');await editImage(imageForRequest,q,bubble);}else{try{show(await askAI(q,imageForRequest),'nexus');}catch(error){show(`⚠️ L’analyse de l’image a échoué.\n\n${error.message}`,'nexus');}}}else if(hadDocument){try{show(await askAI(q,'',documentForRequest,fileForRequest?.name||''),'nexus');}catch(error){show(`⚠️ L’analyse du document a échoué.\n\n${error.message}`,'nexus');}}else if(isVideoPrompt(q)){const bubble=showVideoLoading(q);await generateVideo(q,bubble);}else if(isImagePrompt(q)){const bubble=showImageLoading(q);await generateImage(q,bubble);}else{try{show(await askAI(q),'nexus');}catch(error){show(`⚠️ Le serveur IA n’a pas répondu.\n\n${error.message}`,'nexus');}}}}catch(error){show(`⚠️ ${error.message||'Une erreur est survenue.'}`,'nexus');}finally{clearSelectedFile();setBusy(false);input.focus();}}
function memoryView(){const memory=brain.getMemory();const items=[];if(memory.prenom)items.push(`Prénom : ${memory.prenom}`);if(memory.ville)items.push(`Ville : ${memory.ville}`);if(memory.preferences)Object.entries(memory.preferences).forEach(([k,v])=>items.push(`${k.replaceAll('_',' ')} : ${v}`));return items.length?`🧠 **Mémoire de cet appareil**\n\n${items.join('\n')}\n\n🖥️ Appareil : ${deviceId.slice(0,8)}`:`🧠 **Mémoire de cet appareil**\n\nMa mémoire est encore vide.\n\n🖥️ Appareil : ${deviceId.slice(0,8)}`;}
document.getElementById('memoryButton')?.addEventListener('click',()=>show(memoryView(),'nexus'));document.getElementById('helpButton')?.addEventListener('click',()=>show('🧠 **Nexus AI V2.6**\n\nLe bouton 📎 ouvre maintenant un seul menu avec la création de code, la création d’image et le téléchargement de fichiers. Les téléchargements acceptent les images, PDF, Word (.docx), LibreOffice (.odt) et fichiers texte.','nexus'));document.getElementById('clearMemoryButton')?.addEventListener('click',()=>{clearMemory();saveMemory(createMemory());show('🧹 La mémoire de **cet appareil** a été effacée.','nexus');});document.getElementById('newChatButton')?.addEventListener('click',()=>{history=[];clearConversation();render();input.focus();});document.getElementById('menuCodeButton')?.addEventListener('click',()=>{attachMenu.hidden=true;input.value='Écris-moi du code ';input.focus();});document.getElementById('menuImageButton')?.addEventListener('click',()=>{attachMenu.hidden=true;input.value='Crée une image de ';input.focus();});document.getElementById('menuVideoButton')?.addEventListener('click',()=>{attachMenu.hidden=true;input.value='Crée une vidéo de ';input.focus();});document.getElementById('menuUploadButton')?.addEventListener('click',()=>{attachMenu.hidden=true;fileInput?.click();});document.getElementById('imageUploadButton')?.addEventListener('click',event=>{event.stopPropagation();attachMenu.hidden=!attachMenu.hidden;});document.addEventListener('click',event=>{if(attachMenu&&!attachMenu.hidden&&!event.target.closest('.attach-menu-wrap'))attachMenu.hidden=true;});fileInput?.addEventListener('change',async event=>{const file=event.target.files?.[0];if(!file)return;try{await handleFile(file);}catch(error){clearSelectedFile();show(`⚠️ ${error.message}`,'nexus');}finally{event.target.value='';}});document.getElementById('removeFileButton')?.addEventListener('click',clearSelectedFile);send.addEventListener('click',()=>sendText(input.value));input.addEventListener('keydown',event=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();sendText(input.value);}});input.addEventListener('input',()=>{input.style.height='auto';input.style.height=`${Math.min(input.scrollHeight,200)}px`;});window.addEventListener('error',event=>console.error('Nexus IA runtime error:',event.error||event.message));render();
