(()=>{"use strict";
const VERSION="V0.2",STORAGE_KEY="nexus-v0-memory",chat=document.querySelector("#chat"),form=document.querySelector("#composer"),input=document.querySelector("#prompt");
const state={history:[],turn:0,memory:loadMemory(),lastIntent:null,lastTopic:null,sessionStarted:Date.now(),facts:loadFacts()};
function loadFacts(){try{return JSON.parse(localStorage.getItem("nexus-v0-facts")||"{}")}catch{return{}}}
function saveFacts(){try{localStorage.setItem("nexus-v0-facts",JSON.stringify(state.facts))}catch{}}
function rememberFact(key,value){if(value){state.facts[key]=String(value).trim();saveFacts()}}
function levenshtein(a,b){const m=a.length,n=b.length,dp=Array.from({length:m+1},(_,i)=>[i]);for(let j=1;j<=n;j++)dp[0][j]=j;for(let i=1;i<=m;i++){for(let j=1;j<=n;j++)dp[i][j]=Math.min(dp[i-1][j]+1,dp[i][j-1]+1,dp[i-1][j-1]+(a[i-1]===b[j-1]?0:1))}return dp[m][n]}
function similarity(a,b){const d=levenshtein(a,b);return 1-d/Math.max(a.length,b.length,1)}
function words(text){return normalize(text).split(/[^a-z0-9à-ÿ]+/).filter(Boolean)}
function correctCommonTypos(n){const fixes={"bjr":"bonjour","slt":"salut","bonjor":"bonjour","bonjou":"bonjour","mercii":"merci","merciii":"merci","calclule":"calcule","calculez":"calcule","ameliore":"ameliore","inteligent":"intelligent","memorie":"memoire","memoir":"memoire"};return words(n).map(w=>fixes[w]||w).join(" ")}

function loadMemory(){try{return new Map(Object.entries(JSON.parse(localStorage.getItem(STORAGE_KEY)||"{}")))}catch{return new Map()}}
function saveMemory(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(Object.fromEntries(state.memory)))}catch{}}
function normalize(s){return String(s).toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[’]/g,"'").replace(/\s+/g," ").trim()}
function hasWholePhrase(s,phrase){const target=words(phrase),source=words(s);if(!target.length)return false;for(let i=0;i<=source.length-target.length;i++){let ok=true;for(let j=0;j<target.length;j++)if(source[i+j]!==target[j]){ok=false;break}if(ok)return true}return false}
function hasAny(s,a){return a.some(x=>hasWholePhrase(s,x))}
function remember(text){const rules=[[/\bje m'appelle\s+([a-zà-ÿ][a-zà-ÿ -]{1,35})/i,"name"],[/\bmon nom est\s+([a-zà-ÿ][a-zà-ÿ -]{1,35})/i,"name"],[/\bj'aime\s+([^.!?]{2,100})/i,"likes"],[/\bje prefere\s+([^.!?]{2,100})/i,"preference"],[/\bmon projet est\s+([^.!?]{2,120})/i,"project"]];for(const [re,key] of rules){const m=text.match(re);if(m){state.memory.set(key,m[1].trim());saveMemory()}}}
function memoryText(){const a=[];if(state.memory.has("name"))a.push("prénom: "+state.memory.get("name"));if(state.memory.has("likes"))a.push("goûts: "+state.memory.get("likes"));if(state.memory.has("preference"))a.push("préférence: "+state.memory.get("preference"));if(state.memory.has("project"))a.push("projet: "+state.memory.get("project"));if(state.facts.city)a.push("ville: "+state.facts.city);
if(state.facts.language)a.push("langue: "+state.facts.language);
return a.join(" • ")}
function mathTokens(expr){const out=[],re=/\s*(\d+(?:\.\d+)?|[()+\-*/%^])\s*/g;let i=0,m;while((m=re.exec(expr))){if(m.index!==i)return null;out.push(m[1]);i=re.lastIndex}return i===expr.length?out:null}
function calculate(expr){expr=expr.replace(/,/g,".").trim();if(!expr||expr.length>120)return null;const t=mathTokens(expr);if(!t)return null;const values=[],ops=[],prec={"+":1,"-":1,"*":2,"/":2,"%":2,"^":3},right={"^":true};const apply=()=>{const op=ops.pop(),b=values.pop(),a=values.pop();if(a===undefined||b===undefined)return false;if(op==="+")values.push(a+b);else if(op==="-")values.push(a-b);else if(op==="*")values.push(a*b);else if(op==="/"){if(b===0)throw Error("division");values.push(a/b)}else if(op==="%"){if(b===0)throw Error("division");values.push(a%b)}else if(op==="^")values.push(Math.pow(a,b));return true};try{let unary=true;for(const x of t){if(/^\d/.test(x)){values.push(Number(x));unary=false}else if(x==="("){ops.push(x);unary=true}else if(x===")"){while(ops.length&&ops.at(-1)!=="(")if(!apply())return null;if(ops.pop()!=="(")return null;unary=false}else{if(unary&&x==="-")values.push(0);while(ops.length&&ops.at(-1)!=="("&&(prec[ops.at(-1)]>prec[x]||(prec[ops.at(-1)]===prec[x]&&!right[x])))if(!apply())return null;ops.push(x);unary=true}}while(ops.length)if(ops.at(-1)==="("||!apply())return null;const v=values[0];return values.length===1&&Number.isFinite(v)?v:null}catch{return null}}
function extractUnitConversion(text){const n=normalize(text).replace(/,/g,".");const m=n.match(/^(?:convertis|convertir|conversion de)?\s*(\d+(?:\.\d+)?)\s*(km|m|cm|mm|kg|g|l|ml|h|min|s)\s+(?:en|vers)\s*(km|m|cm|mm|kg|g|l|ml|h|min|s)\s*$/);if(!m)return null;const v=Number(m[1]),from=m[2],to=m[3];const groups={length:{km:1000,m:1,cm:.01,mm:.001},mass:{kg:1000,g:1},volume:{l:1,ml:.001},time:{h:3600,min:60,s:1}};let group=null;for(const g of Object.values(groups))if(g[from]!==undefined&&g[to]!==undefined)group=g;if(!group)return null;const result=v*group[from]/group[to];return {value:v,from,to,result:Number(result.toPrecision(12))}}
function localTimeText(){const d=new Date();return "Il est "+d.toLocaleTimeString("fr-FR",{hour:"2-digit",minute:"2-digit"})+" le "+d.toLocaleDateString("fr-FR",{weekday:"long",day:"numeric",month:"long"})+"."}
function extractMath(text){const n=normalize(text);if(!/(\bcalcule\b|\bcalculer\b|\bcombien font\b|\bresultat de\b|^[\d\s()+\-*/%,.^]+$)/.test(n))return null;const expr=text.replace(/calcule(?:r)?|combien font|résultat de|resultat de/gi,"").replace(/[?=]/g,"").trim();if(!/^[\d\s()+\-*/%,.^]+$/.test(expr))return null;return calculate(expr)}
function random(a){return a[Math.floor(Math.random()*a.length)]}
const intents=[
{id:"time",words:["quelle heure","heure actuelle","heure"],answer:()=>localTimeText()},
{id:"date",words:["quelle date","date actuelle","quel jour sommes nous","on est quel jour"],answer:()=>new Date().toLocaleDateString("fr-FR",{weekday:"long",day:"numeric",month:"long",year:"numeric"})+"."},
{id:"conversion",words:["convertis","convertir","conversion"],answer:()=>null},
{id:"greeting",words:["bonjour","salut","hello","coucou","bonsoir","hey"],answer:()=>random(["Bonjour ! 👋 Je suis prêt.","Salut ! 👋 Nexus Core est actif.","Bonjour ! Que veux-tu construire aujourd'hui ?"])},
{id:"thanks",words:["merci","thanks"],answer:()=>random(["Avec plaisir ! 😊","Pas de souci !","Content de pouvoir t'aider."])},
{id:"identity",words:["qui es tu","qui es-tu","tu es qui","presente toi","présente toi","présente-toi"],answer:()=>"Je suis Nexus IA "+VERSION+", un moteur local exécuté dans ton navigateur. Je n'appelle aucune API externe et je n'utilise aucune clé API."},
{id:"version",words:["quelle version","quel version","ta version","version actuelle","version"],answer:()=>"Nous sommes sur Nexus IA "+VERSION+". Cette V0 est la fondation locale du projet."},
{id:"api",words:["api","clé api","cle api","openai","gemini","api externe"],answer:()=>"La règle de cette V0 est simple : aucune API externe et aucune clé API. Tout le moteur actuel tourne localement dans le navigateur."},
{id:"capabilities",words:["que peux tu faire","que peux-tu faire","tu peux faire quoi","tes capacités","capacites","aide","help"],answer:()=>"Je peux déjà :\n• discuter avec un moteur local\n• conserver une mémoire locale\n• comprendre plusieurs formulations\n• calculer des expressions\n• suivre le sujet récent\n• gérer des commandes locales\n\nLa prochaine marche sera un modèle local, toujours sans API distante."},
{id:"memory",words:["que sais tu de moi","que sais-tu de moi","tu te souviens","tes souvenirs","ma memoire","mémoire"],answer:()=>memoryText()?"Voici ce que Nexus Core a mémorisé localement :\n"+memoryText():"Je n'ai encore rien mémorisé de personnel. Tu peux dire « Je m'appelle … »."},
{id:"forget",words:["oublie tout","efface ta memoire","efface ma memoire","oublie ma memoire","oublie tout de moi"],answer:()=>{state.memory.clear();saveMemory();return"Ma mémoire locale a été effacée. 🧹"}},
{id:"status",words:["ça marche","ca marche","tu fonctionnes","systeme","système","etat","état","core"],answer:()=>"Nexus Core "+VERSION+" est actif.\nTours de conversation : "+state.turn+".\nRéseau externe : désactivé."},
{id:"math",words:["calcule","calculer","combien font","résultat de","resultat de"],answer:()=>null},
{id:"project",words:["projet","developpement","développement","coder","code","programmation","programme"],answer:()=>"Pour Nexus IA, la priorité de la V0 est de garder un Core local modulaire et de ne pas mélanger l'interface avec le moteur."},
{id:"intelligence",words:["plus intelligent","intelligent","intelligence","améliore","ameliore","meilleur","raisonner"],answer:()=>"Oui. 🧠 La base peut encore être améliorée sans API : meilleur traitement du langage, mémoire, contexte, outils locaux et surtout un LLM exécuté localement. Des règles seules ne deviennent toutefois pas magiquement un LLM."},
{id:"goodbye",words:["au revoir","a plus","à plus","bye","bonne nuit"],answer:()=>random(["À plus ! 👋","À bientôt !","Nexus Core reste prêt."])}
];
function scoreIntent(n,intent){let score=0;for(const raw of intent.words){const w=normalize(raw);if(n===w)score+=10;else if(hasWholePhrase(n,w))score+=Math.max(2,Math.min(7,w.length/4));else if(w.length>=5&&similarity(n,w)>=.78)score+=3}return score}
function detectIntent(text){const n=correctCommonTypos(normalize(text));let best={intent:null,score:0};for(const intent of intents){const s=scoreIntent(n,intent);if(s>best.score)best={intent,score:s}}return best.score>=2?best.intent:null}
function contextualAnswer(text){const n=correctCommonTypos(normalize(text));
if(/^(quelle heure|il est quelle heure|heure actuelle|heure il est)/.test(n))return localTimeText();
if((n==="qui suis je"||n==="qui suis-je")&&state.memory.has("name"))return"Tu m'as indiqué que ton prénom est "+state.memory.get("name")+".";
if(/^(ou j'habite|ou habite je|ma ville)/.test(n)&&state.facts.city)return"Tu m'as indiqué habiter à "+state.facts.city+".";
if((n==="oui"||n==="non"||n==="ok"||n==="d'accord"||n==="vas-y")&&state.lastIntent==="intelligence")return"Parfait. Pour la suite, on peut renforcer le Core par modules indépendants : compréhension → contexte → mémoire → outils → génération.";if((n.includes("et apres")||n.includes("et après")||n==="ensuite")&&state.lastTopic)return"On était sur « "+state.lastTopic+" ». La suite logique est de renforcer ce module sans ajouter d'API externe.";return null}
function fallback(text){const n=correctCommonTypos(normalize(text)),c=contextualAnswer(text);if(c)return c;if(n.includes("comment")&&n.includes("nexus"))return"Pour Nexus IA, je recommande de séparer l'interface, le Core, la mémoire et les outils. Cette séparation permettra d'améliorer chaque partie sans casser le reste.";if(n.endsWith("?"))return"Je comprends la question, mais la V0 ne possède pas encore les connaissances générales suffisantes pour donner une réponse fiable. Je préfère te le dire plutôt que d'inventer.";if(text.length<4)return"Je t'écoute. 👂";return"Je comprends ta demande, mais mon moteur local V0 n'a pas encore le module nécessaire pour y répondre précisément. Cette limite est réelle : je ne vais pas inventer une réponse."}
function respond(text){remember(text);
const raw=text.trim(),n=normalize(raw);
const city=n.match(/(?:j'habite|je vis|ma ville est)\s+(?:a |à )?(.{2,50})$/i);if(city)rememberFact("city",city[1].replace(/[.!?]+$/,""));
const lang=n.match(/(?:je parle|ma langue est)\s+([a-zà-ÿ -]{2,30})$/i);if(lang)rememberFact("language",lang[1].replace(/[.!?]+$/,""));
const conversion=extractUnitConversion(raw);if(conversion){state.lastIntent="conversion";state.lastTopic="conversion";return conversion.value+" "+conversion.from+" = "+conversion.result+" "+conversion.to+"."}
const math=extractMath(text);if(math!==null){state.lastIntent="math";state.lastTopic="calcul";return"Le résultat est "+math+"."}const intent=detectIntent(text);if(intent){state.lastIntent=intent.id;if(intent.id==="forget"){state.memory.clear();state.facts={};saveMemory();saveFacts();return"Ma mémoire locale et mes faits enregistrés ont été effacés. 🧹"}if(!["greeting","thanks","identity","version","api","status","memory","forget","time","date","conversion"].includes(intent.id))state.lastTopic=text.slice(0,80);const a=intent.answer();return a||fallback(text)}const c=contextualAnswer(text);if(c)return c;state.lastTopic=text.slice(0,80);return fallback(text)}
function addMessage(text,role){const article=document.createElement("article");article.className="message "+role;const avatar=document.createElement("div");avatar.className="avatar";avatar.textContent=role==="assistant"?"N":"U";const body=document.createElement("div");if(role==="assistant"){const strong=document.createElement("strong");strong.textContent="Nexus IA";body.appendChild(strong)}const p=document.createElement("p");p.textContent=text;body.appendChild(p);article.append(avatar,body);chat.appendChild(article);chat.scrollTop=chat.scrollHeight}
function setBusy(b){const button=form.querySelector("button");button.disabled=b;button.textContent=b?"…":"➤"}
form.addEventListener("submit",event=>{event.preventDefault();const text=input.value.trim();if(!text)return;addMessage(text,"user");state.history.push({role:"user",text});state.turn++;input.value="";input.style.height="auto";setBusy(true);const answer=respond(text);state.history.push({role:"assistant",text:answer});setTimeout(()=>{addMessage(answer.replace(/\*\*/g,""),"assistant");setBusy(false);input.focus()},140)});
input.addEventListener("input",()=>{input.style.height="auto";input.style.height=Math.min(input.scrollHeight,160)+"px"});
window.NexusCore={version:VERSION,state,respond,calculate,detectIntent,normalize,similarity,convert:extractUnitConversion};
})();