const VERSION = '3.6.0';

export function buildNexusIdentity(){return['IDENTITÉ NEXUS CORE V3.6 : tu es le moteur central de Nexus IA.','Tu analyses l’objectif, les contraintes, le contexte et les capacités disponibles avant de choisir une stratégie.','Le cœur Nexus reste indépendant du fournisseur de modèle et peut continuer avec un moteur de secours configuré si le modèle principal devient indisponible.','Tu restes honnête : aucune action, vérification, navigation, exécution ou observation ne doit être prétendue si elle n’a pas réellement eu lieu.'].join('\n')}
export function buildReasoningPolicy(){return['POLITIQUE NEXUS CORE V3.6 :','- Décompose mentalement les tâches complexes en étapes utiles avant de répondre.','- Pour une mission, identifie objectif, sous-objectifs, dépendances, contraintes et critères de réussite.','- Vérifie les résultats importants avant de les présenter.','- Utilise le contexte fourni sans mélanger les sessions.','- Sépare clairement faits, hypothèses et propositions.','- Si une information manque, demande-la ou signale précisément la limite.','- Ne révèle pas de raisonnement interne privé : expose seulement les conclusions et les étapes utiles.','- Si le moteur principal est indisponible, continue avec le moteur de secours sans changer arbitrairement la mission ni inventer ses capacités.'].join('\n')}
export function buildFutureEngineContract(){return{version:VERSION,architecture:'nexus-core',orchestration:true,missionMode:true,missionEngine:'3.6',modelResilience:true,primaryModel:'gpt-5.6-sol',fallbackReady:true,contextAdvisor:true,selfCorrection:true,specializedAgents:true,agentOrchestration:true,privacyBoundary:'session-scoped',verification:true,multimodalReady:true}}
function uniqueSteps(steps){return[...new Set(steps)].slice(0,6)}
export function createMissionExecution(message){const plan=planMission(message),now=new Date().toISOString(),steps=plan.steps.map((label,index)=>({id:'step-'+(index+1),order:index+1,label,status:'pending',startedAt:null,completedAt:null}));return{id:'mission-'+Date.now().toString(36),status:plan.isMission?'pending':'completed',priority:plan.priority,type:plan.type,createdAt:now,startedAt:null,completedAt:plan.isMission?null:now,activeStep:plan.isMission?steps[0]?.id||null:null,steps}}
export function startMissionExecution(mission){if(!mission?.steps?.length)return mission;const first=mission.steps.find(step=>step.status==='pending'),startedAt=new Date().toISOString();return{...mission,status:'running',startedAt:mission.startedAt||startedAt,activeStep:first?.id||null,steps:mission.steps.map(step=>step.id===first?.id?{...step,status:'running',startedAt:step.startedAt||startedAt}:step)}}
export function completeMissionExecution(mission){const completedAt=new Date().toISOString();return{...mission,status:'completed',activeStep:null,completedAt,steps:mission.steps.map(step=>({...step,status:'completed',startedAt:step.startedAt||mission.startedAt||completedAt,completedAt:step.completedAt||completedAt}))}}
export function failMissionExecution(mission,errorMessage=''){const failedAt=new Date().toISOString();return{...mission,status:'failed',activeStep:null,completedAt:failedAt,error:String(errorMessage||'Mission interrompue.').slice(0,500),steps:mission.steps.map(step=>step.status==='running'?{...step,status:'failed',completedAt:failedAt}:step)}}
export function planMission(message){const text=String(message||'').trim(),lower=text.toLowerCase(),isMission=text.length>350||/\b(site|application|projet|système|architecture|workflow|diagnostic|audit|comparaison|organise|planifie|construis|développe|réalise|crée)\b/i.test(text);if(!isMission)return{isMission:false,type:'simple',priority:'normal',steps:['Comprendre la demande','Répondre']};const steps=['Comprendre l’objectif et les contraintes'];if(/\b(site|application|projet|système|architecture|workflow|code|roblox|programme|développe)\b/i.test(lower)){steps.push('Définir l’architecture et les composants');steps.push('Construire ou modifier les éléments nécessaires')}else if(/\b(compare|comparaison|choisir|différence|analyse|audit)\b/i.test(lower)){steps.push('Identifier les critères et les informations utiles');steps.push('Comparer les éléments de façon structurée')}else if(/\b(plan|organise|planifie|voyage|programme|planning)\b/i.test(lower)){steps.push('Structurer les étapes, contraintes et dépendances');steps.push('Construire un plan exécutable')}else{steps.push('Décomposer le problème en sous-tâches');steps.push('Produire la solution étape par étape')}steps.push('Vérifier la cohérence du résultat');steps.push('Présenter le résultat et les prochaines actions utiles');return{isMission:true,type:'mission',priority:text.length>1200?'high':'normal',steps:uniqueSteps(steps)}}
